from common import config

BASE_TOPIC_PATH = "dayeye"
TOPIC_SEPARATOR = "/"
VIDEO_STREAM_TOPIC = BASE_TOPIC_PATH + TOPIC_SEPARATOR + "capture"
LOCAL_FACES_TOPIC = BASE_TOPIC_PATH + TOPIC_SEPARATOR + "local_faces"
DEBUG_TOPIC = BASE_TOPIC_PATH + TOPIC_SEPARATOR + "debug"
MAIN_TOPIC = BASE_TOPIC_PATH + TOPIC_SEPARATOR + "main"